schema_version = "1.0.0"

id = "flatcut"
version = "1.1.1"
name = "Flatcut"
tagline = "Export wood parts to G-code/SVG for laser and CNC 2D cutting"
maintainer = "Itamoto Shintaro (GitHub: @itashin0501)"
type = "add-on"
website = "https://plaft.studio/"

tags = ["Import-Export", "Object"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2026 Itamoto Shintaro",
]
